services:
  - type: web
    name: shopsphere-backend
    env: node
    rootDir: backend-ShopSphere
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: FRONTEND_URL_2
        sync: false
